pipeline:

  test:
    image: golang:1.12
    commands:
      - bash cli/get_coverpro_file.sh
    secrets: [CODECOV_TOKEN]

  build:
    image: plugins/docker
    repo: username502/quote-board
    secrets: [docker_username, docker_password]
    build_args:
      - DRONE=${DRONE}
      - DRONE_TAG=${DRONE_TAG}
      - DRONE_COMMIT=${DRONE_COMMIT}
      - DRONE_BRANCH=${DRONE_BRANCH}
